// Decode JWT token to see its structure
const token = "eyJhbGciOiJIUzI1NiIsImtpZCI6Iml5L1NjT2RSZ3FieG9SSFYiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3pra2Ruc2x1cHFucGlvbHRqcGV1LnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiI1NzNkNjUzNS1hNDgwLTRlNzUtOTg1Yi04ODIwZTE2NDM3YWQiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzU0MjkxNTA4LCJpYXQiOjE3NTQyODc5MDgsImVtYWlsIjoiY2VvQHNpZ2EuY29tIiwicGhvbmUiOiIiLCJhcHBfbWV0YWRhdGEiOnsicHJvdmlkZXIiOiJlbWFpbCIsInByb3ZpZGVycyI6WyJlbWFpbCJdfSwidXNlcl9tZXRhZGF0YSI6eyJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwiZnVsbF9uYW1lIjoiQ0VPIFNJR0EiLCJyb2xlIjoiQ0VPIn0sInJvbGUiOiJhdXRoZW50aWNhdGVkIiwiYWFsIjoiYWFsMSIsImFtciI6W3sibWV0aG9kIjoicGFzc3dvcmQiLCJ0aW1lc3RhbXAiOjE3NTQyODc5MDh9XSwic2Vzc2lvbl9pZCI6ImNmNjg1YmEwLWYyZGMtNDFhMS1hYjlmLTRjZDg1NDcyNGJkZiIsImlzX2Fub255bW91cyI6ZmFsc2V9.kboZ8XlNXLhmystR3CaSF83meY2VjczQNCa6TVrv8a0";

// Decode the payload (second part)
const payload = token.split('.')[1];
const decoded = JSON.parse(Buffer.from(payload, 'base64').toString());

console.log("JWT Token payload:");
console.log(JSON.stringify(decoded, null, 2));